modLoader = "javafml"
loaderVersion = "[${loader},)"
license = "Insert License Here"

[[mods]]
modId = "itemplacer"
version = "${version}"
displayName = "${name}"
authors = "akicater"
description = "${description}"
logoFile = "assets/item-placer/logo.png"

[[dependencies.itemplacer]]
modId = "forge"
mandatory = true
versionRange = "[${loader},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemplacer]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemplacer]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"
