modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "itemplacer"
version = "${version}"
displayName = "Item placer"
authors = "akicater"
description = '''
Place any item on any block side
'''
logoFile = "assets/item-placer/logo.png"

[[dependencies.itemplacer]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemplacer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemplacer]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "itemplacer.mixins.json"
